---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: azureuser

  roles:
    - common

- name: configure and Deploy Jazz Authentication Server 
  hosts: jas
  remote_user: azureuser

  roles:
    - jas

# - name: configure and Deploy Engineering Workflow Management Server 
#   hosts: ewm
#   remote_user: azureuser

#   roles:
#     - ewm